name: update profile [manual]

on: 
  workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: fetch repository
              uses: actions/checkout@v2

            - name: setup python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.8.15"

            - name: install python packages
              run: |
                  python -m pip install --upgrade pip
                  pip install python-dateutil requests

            - name: fetching recent activity
              env:
                  GH_USERNAME: ${{ secrets.GH_USERNAME }}
                  GH_EMAIL: ${{ secrets.GH_EMAIL }}
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
              run: python fetch.py

            - name: update reademe.md
              env:
                  GH_USERNAME: ${{ secrets.GH_USERNAME }}
                  GH_EMAIL: ${{ secrets.GH_EMAIL }}
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}              
              run: |
                  git config --global user.name github-actions
                  git config --global user.email '#'
                  git remote set-url origin https://x-access-token:$GH_TOKEN@github.com/$GITHUB_REPOSITORY
                  git add -A
                  git commit --amend --no-edit
                  git push --force
